# Site settings
title: Official page for Language Server Protocol
description: >
  Language Server Protocol documentation and specification page.

baseurl: /language-server-protocol # the subpath of your site, e.g. /blog/
url: https://microsoft.github.io/language-server-protocol/ # the base hostname & protocol for your site
git_address: https://github.com/Microsoft/language-server-protocol
git_edit_address: https://github.com/Microsoft/language-server-protocol/blob/gh-pages

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - github-pages
  - jemoji


exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - resources

timezone: Europe/Zurich

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _implementors
    type: implementors
  values:
    layout: implementors
    sectionid: implementors

- scope:
    path: _overviews
    type: overviews
  values:
    layout: overviews
    sectionid: overviews

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  implementors:
    permalink: /:collection/:path/
    output: true
  overviews:
    permalink: /:collection/:path/
    output: true
